import type { Metadata } from "next";
import { NextCacheToolbar } from "next-cache-toolbar";
import "next-cache-toolbar/style.css";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {process.env.NODE_ENV === "development" && <NextCacheToolbar />}
      </body>
    </html>
  );
}
